---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: postgresql
spec:
  externalSecretName: postgresql
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: postgresql
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: postgresql
    data:
    - secretKey: postgresql-postgres-password
      remoteRef:
        key: postgresql
        property: postgres-password