---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: postgresql
spec:
  externalSecretName: postgresql
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: postgresql
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: postgresql
    dataFrom:
    - extract:
        key: secret/postgresql

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: keycloak
spec:
  externalSecretName: keycloak
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: keycloak
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: keycloak
    dataFrom:
    - extract:
        key: secret/keycloak