---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: postgresql
spec:
  externalSecretName: postgresql
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: postgresql
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: postgresql
    dataFrom:
    - extract:
        key: secret/postgresql

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: keycloak
spec:
  externalSecretName: keycloak
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: keycloak
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: keycloak
    dataFrom:
    - extract:
        key: secret/keycloak

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: alertmanager
spec:
  externalSecretName: alertmanager
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: prometheus
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: alertmanager
    dataFrom:
    - extract:
        key: secret/alertmanager

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: grafana-auth
spec:
  externalSecretName: grafana-auth
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: grafana
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: grafana-auth
    dataFrom:
    - extract:
        key: secret/grafana

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: elasticsearch
spec:
  externalSecretName: elasticsearch
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: elasticsearch
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: elasticsearch
    dataFrom:
    - extract:
        key: secret/elasticsearch

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: kibana
spec:
  externalSecretName: kibana
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kibana
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: kibana
    dataFrom:
    - extract:
        key: secret/kibana