apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.ssang.io
      version: v2
      path: secret
      auth:
        kubernetes:
          mountPath: kubernetes
          role: cluster-secret-store
          serviceAccountRef:
            name: cluster-secret-store
            namespace: external-secrets