---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: postgresql
spec:
  externalSecretName: postgresql
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: postgresql
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: postgresql
    dataFrom:
    - extract:
        key: secret/postgresql

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: pgadmin
spec:
  externalSecretName: pgadmin
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: pgadmin
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: pgadmin
    dataFrom:
    - extract:
        key: secret/pgadmin

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: keycloak
spec:
  externalSecretName: keycloak
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: keycloak
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: keycloak
    dataFrom:
    - extract:
        key: secret/keycloak

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: alertmanager
spec:
  externalSecretName: alertmanager
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: prometheus
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: alertmanager
    dataFrom:
    - extract:
        key: secret/alertmanager

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: grafana
spec:
  externalSecretName: grafana
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: grafana
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: grafana
    dataFrom:
    - extract:
        key: secret/grafana