apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: default
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
      - https://argocd.ssang.io
      - https://vault.ssang.io/ui/
      - https://keycloak.ssang.io