apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:19.0.2
        args:
        - start
        - --auto-build
        - --db=postgres
        env:
        - name: KC_HOSTNAME
          value: keycloak.ssang.io
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: KC_DB_URL_HOST
        - name: KC_DB_USER
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: KC_DB_USER
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: KC_DB_PASSWORD
        - name: KC_PROXY
          value: "edge"
        ports:
        - name: http
          containerPort: 8080