apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: postgresql
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postgresql-password
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secret/postgresql
      property: POSTGRES_PASSWORD
  refreshInterval: 1h