apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.20.8
    helm:
      releaseName: fluent-bit
      values: |
        config:
          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host elasticsearch-master.elasticsearch.svc.cluster.local
                Logstash_Format On
                Retry_Limit False
            [OUTPUT]
                Name es
                Match host.*
                Host elasticsearch-master.elasticsearch.svc.cluster.local
                Logstash_Format On
                Logstash_Prefix node
                Retry_Limit False
  destination:
    server: https://kubernetes.default.svc
    namespace: fluent-bit
  syncPolicy:
    syncOptions:
    - CreateNamespace=true