apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.38.7
    helm:
      releaseName: grafana
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
          hosts:
          - grafana.ssang.io
          tls:
          - hosts:
            - grafana.ssang.io
            secretName: grafana-ssang-io-tls-cert
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true