apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 7.17.3
    helm:
      releaseName: kibana
      values: |
        elasticsearchHosts: http://elasticseach-master.elasticsearch.svc.cluster.local:9200
  destination:
    server: https://kubernetes.default.svc
    namespace: kibana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true