apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 7.17.3
    helm:
      releaseName: kibana
      values: |
        elasticsearchHosts: http://elasticsearch-master.elasticsearch.svc.cluster.local:9200
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
          hosts:
          - host: kibana.ssang.io
            paths: []
          tls:
          - hosts:
            - kibana.ssang.io
            secretName: kibana-ssang-io-tls-cert
  destination:
    server: https://kubernetes.default.svc
    namespace: kibana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true