apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ssang4/monorepo.git
    targetRevision: HEAD
    path: argocd/pgadmin
  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin
  syncPolicy:
    syncOptions:
    - CreateNamespace=true