apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 15.13.0
    helm:
      releaseName: prometheus
      values: |
        serverFiles:
          alerting_rules.yml:
            groups:
            - name: node_memory
              rules:
              - alert: HighMemoryUtilization
                expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < 0.2
                for: 5m
                labels:
                  severity: warning
                annotations:
                  summary: Memory utilization is {{ (1 - $value) * 100 }}%
            - name: node_cpu
              rules:
              - alert: HighCpuUtilization
                expr: avg without (cpu) (irate(node_cpu_seconds_total{mode="idle"}[5m])) < 0.2
                for: 5m
                labels:
                  severity: warning
                annotations:
                  summary: Cpu utilization is {{ (1 - $value) * 100 }}%
            - name: node_disk
              rules:
              - alert: LowDiskSpace
                expr: node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.2
                for: 5m
                labels:
                  severity: warning
                annotations:
                  summary: Disk space is {{ (1 - $value) * 100 }}% full
        alertmanager:
          configFromSecret: alertmanager
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true