apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: default
spec:
  version: 8.4.2
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: 0.6
              memory: 800Mi
            limits:
              cpu: 0.6
              memory: 800Mi
  http:
    tls:
      selfSignedCertificate:
        disabled: true