apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: default
spec:
  version: 8.4.2
  count: 1
  elasticsearchRef:
    name: default
  http:
    tls:
      selfSignedCertificate:
        disabled: true