crds:
  install: false

server:
  extraArgs:
  - --insecure
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
    - argocd.ssang.io
    tls:
    - hosts:
      - argocd.ssang.io
      secretName: argocd-ssang-io-tls-cert
  config:
    url: https://argocd.ssang.io
    admin.enabled: "false"
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.ssang.io/realms/master
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email
  rbacConfig:
    policy.csv: |
      g, argocd-admin, role:admin

controller:
  priorityClassName: system-cluster-critical