---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-primary-data
  namespace: postgresql
  annotations:
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: b845b55b-3857-11ed-9957-0a58ac14d00f
    volumeAttributes:
      com.digitalocean.cis/noformat: "true"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-primary-data
  namespace: postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: do-block-storage